api/urls.py
from django.urls import path, include
from rest_framework import routers
from canvas.serializer import UserViewSet
from main.serializer import DepartmentViewSet, ProfileViewSet
from event.serializer import EventViewSet
from inbox.serializer import InboxViewSet
from dashboard.serializer import (
    ProfessorViewSet,
    CourseViewSet,
    EnrollmentViewSet,
    StudentViewSet,
)
from announcement.serializer import AnnouncementViewSet
from todo.serializer import TodoViewSet

router = routers.DefaultRouter()
router.register(r"users", UserViewSet)
router.register(r"departments", DepartmentViewSet)
router.register(r"profiles", ProfileViewSet)
router.register(r"events", EventViewSet)
router.register(r"inboxes", InboxViewSet)
router.register(r"professors", ProfessorViewSet)
router.register(r"courses", CourseViewSet)
router.register(r"enrollments", EnrollmentViewSet)
router.register(r"students", StudentViewSet)
router.register(r"announcements", AnnouncementViewSet)
router.register(r"todos", TodoViewSet)

urlpatterns = [
    path("", include(router.urls)),
]

canvas/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views


# Custom 400.html BAD REQUEST handler
handler400 = views.custom_400_view

# Custom 403.html PERMISSION DENIED handler
handler403 = views.custom_403_view

# Custom 404.html PAGE NOT FOUND handler
handler404 = views.custom_404_view

# Custom 500.html SERVER ERROR handler
handler500 = views.custom_500_view


urlpatterns = [
    path("", include("dashboard.urls")),
    path("grappelli/", include("grappelli.urls")),
    path("admin/", admin.site.urls),
    path("login/", views.LoginPageView.as_view(), name="login"),
    path("logout/", views.LogoutPageView.as_view(), name="logout"),
    path("profile/", views.ProfilePageView.as_view(), name="profile"),
    path("security/", views.SecurityPageView.as_view(), name="security"),
    path("api-auth/", include("rest_framework.urls"), name="rest_framework"),
    path("announcements/", include("announcement.urls")),
    path("grades/", include("grade.urls")),
    path("inbox/", include("inbox.urls")),
    path("event/", include("event.urls")),
    path("todo/", include("todo.urls")),
    path("api/", include("api.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/forms.py
from django import forms
from django.contrib.auth.forms import PasswordChangeForm
from .models import Profile


class ProfileForm(forms.ModelForm):

    first_name = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "type": "text",
                "class": "form-control",
                "placeholder": "First Name",
                "required": True,
            }
        ),
    )

    middle_name = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "type": "text",
                "class": "form-control",
                "placeholder": "Middle Name",
                "required": True,
            }
        )
    )

    last_name = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "type": "text",
                "class": "form-control",
                "placeholder": "Last Name",
                "required": True,
            }
        )
    )

    email = forms.CharField(
        widget=forms.EmailInput(
            attrs={
                "type": "text",
                "class": "form-control",
                "placeholder": "Email Address",
                "required": True,
            }
        )
    )

    date_of_birth = forms.DateField(
        widget=forms.DateInput(
            attrs={
                "type": "date",
                "class": "form-control",
            }
        )
    )

    gender = forms.CharField(
        widget=forms.Select(
            choices=[("", "---"), ("M", "Male"), ("F", "Female")],
            attrs={
                "type": "text",
                "class": "form-select",
                "placeholder": "Last Name",
                "required": True,
            },
        )
    )

    contact_number = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "type": "text",
                "class": "form-control",
                "placeholder": "Contact No",
                "required": True,
            }
        )
    )

    bio = forms.CharField(
        widget=forms.Textarea(
            attrs={
                "type": "text",
                "class": "form-control",
                "placeholder": "Your Bio",
                "required": True,
            }
        )
    )

    city = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "type": "text",
                "class": "form-control",
                "placeholder": "City",
                "required": True,
            }
        )
    )

    province = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "type": "text",
                "class": "form-control",
                "placeholder": "Province",
                "required": True,
            }
        )
    )

    country = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "type": "text",
                "class": "form-control",
                "placeholder": "country",
                "required": True,
            }
        )
    )

    class Meta:
        model = Profile
        fields = [
            "first_name",
            "middle_name",
            "last_name",
            "email",
            "date_of_birth",
            "gender",
            "contact_number",
            "bio",
            "city",
            "province",
            "country",
        ]


class ChangePasswordForm(PasswordChangeForm):

    old_password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "type": "password",
                "class": "form-control",
                "placeholder": "Current password",
                "required": True,
            }
        ),
    )
    new_password1 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "type": "password",
                "class": "form-control",
                "placeholder": "Enter new password",
                "required": True,
            }
        ),
    )
    new_password2 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "type": "password",
                "class": "form-control",
                "placeholder": "Confirm new password",
                "required": True,
            }
        ),
    )

templates/pages/login.html
{% extends "templates/base.html" %}

{% block title %} Login {% endblock title %}

{% block form_content %}
<form method="POST" action="{% if next %} {% url "login" %}?next={{ next }} {% else %} {% url "login" %} {% endif %}">
    {% csrf_token %}
    {% if form.errors %}
    <div class="alert alert-danger" role="alert">
        <p>Username or Password did no match. Try Again!<p>
    </div>
    {% endif %}
    <div class="form-group position-relative has-icon-left mb-4">
        {{ form.username }}
        <div class="form-control-icon">
            <i class="bi bi-person"></i>
        </div>
    </div>
    <div class="form-group position-relative has-icon-left mb-4">
        {{ form.password }}
        <div class="form-control-icon">
            <i class="bi bi-shield-lock"></i>
        </div>
    </div>
    <div class="form-check form-check-lg d-flex align-items-end">
        {{ form.remember_me }}
        <label class="form-check-label text-gray-600" for="flexCheckDefault">
            Keep me logged in
        </label>
    </div>
    <button class="btn btn-primary btn-block btn-lg shadow-lg mt-5" type="submit">Log in</button>
</form>
{% endblock form_content %}

{% block forgot_password %}
<div class="text-center mt-5 text-lg fs-4">
    <p><a class="font-bold" href="auth-forgot-password.html">Forgot password?</a></p>
</div>
{% endblock forgot_password %}

{% block extra_js %}
<script>
    $(function () {
        let messages_list = $(".messages li");

        
        if (messages_list.length) {
            $("#id_username").addClass("is-invalid");
            $("#id_password").addClass("is-invalid");
        }
    })
</script>
{% endblock extra_js %}

templates/pages/profile.html
{% extends "base/base.html" %}

{% load static %}

{% load humanize %}

{% block title %} {{ title }} {% endblock %}

{% block content %}
<section class="container-fluid">
  <div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-content">
                <div class="card-header">
                    <h4 class="card-title">
                        {% if user.profile.is_student %}
                            Basic Student
                        {% elif user.profile.is_professor %}
                            Basic Professor
                        {% else %}
                            Basic Anonymous
                        {% endif %}
                        Profile Information
                    </h4>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-12 col-md-4">
                            <div class="d-flex justify-content-center align-items-center flex-column">
                                <div class="avatar avatar-2xl bg-warning me-3">
                                    <span class="avatar-content">
                                        {{ user.profile.first_name|make_list|first }}{{ user.profile.last_name|make_list|first }}
                                    </span>
                                </div>
                
                                <h5 class="mt-3">{{ user.profile.first_name }} {{ user.profile.last_name }}</h5>
                                <p class="text-small">
                                {{ user.profile.bio }}
                                </p>
                            </div>
                        </div>
                        <div class="pl-5 row col-12 col-md-8">
                            <div class="col-6 col-md-4">
                                <p class="fs-5 fw-medium">Full name</p>
                            </div>
                            <div class="col-6 col-md-8">
                                <p class="fs-5 fst-italic">{{ user.profile.first_name }} {{ user.profile.middle_name }} {{ user.profile.last_name }}</p>
                            </div>
                            <div class="col-6 col-md-4">
                                <p class="fs-5 fw-medium">Email</p>
                            </div>
                            <div class="col-6 col-md-8">
                                <p class="fs-5 fst-italic">{{ user.profile.email }}</p>
                            </div>
                            <div class="col-6 col-md-4">
                                <p class="fs-5 fw-medium">Gender</p>
                            </div>
                            <div class="col-6 col-md-8">
                                <p class="fs-5 fst-italic">
                                    {% if user.profile.gender == "M" %}
                                    Male
                                    {% elif user.profile.gender == "F" %}
                                    Female
                                    {% else %}
                                    Non-Binary
                                    {% endif %}
                                </p>
                            </div>
                            <div class="col-6 col-md-4">
                                <p  class="fs-5 fw-medium">Date of Birth</p>
                            </div>
                            <div class="col-6 col-md-8">
                                <p class="fs-5 fst-italic">{{ user.profile.date_of_birth }}</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
  </div>
  <div class="row">
    <div class="col-12">
        <div class="card">
          <div class="card-header">
              <h4 class="card-title">
                  Class Schedule
              </h4>
              {% comment %} TODO: Add variable for semester {% endcomment %}
              <p class="card-text">Your Class Schedule for: 1st Term 2024-2025</p>
          </div>
          <div class="card-body">
            <div class="table-responsive">
                <table class="table table-hover mb-0">
                    <thead>
                        <tr>
                            <th>CLASS CODE</th>
                            <th>BLOCK</th>
                            <th>SUBJECT</th>
                            <th>TIME</th>
                            <th>DAYS</th>
                            <th>ROOM</th>
                        </tr>
                    </thead>
                    <tbody>
                      {% for course in courses %}
                        <tr>
                          <td class="text-bold-500">{{ course.code }}</td>
                          <td>{{ course.block }}</td>
                          <td class="text-bold-500">{{ course.title }}</td>
                          <td>{{ course.time }}</td>
                          <td>{{ course.days }}</td>
                          <td>{{ course.room }}</td>
                        </tr>
                      {% endfor %}
                    </tbody>
                </table>
            </div>
          </div>
        </div>
      </div>
  </div>
  <div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-header">
            <h4 class="card-title">
                Update your Information
            </h4>
        </div>
        <div class="card-body">
          <form action="{% url 'profile' %}" method="POST">
            {% csrf_token %}
            <div class="row">
              <div class="form-group col-12 col-lg-4">
                <label for="id_first_name" class="form-label">First Name</label>
                {{ form.first_name }}
              </div>
              <div class="form-group col-12 col-lg-4">
                <label for="id_middle_name" class="form-label">Middle Name</label>
                {{ form.middle_name }}
              </div>
              <div class="form-group col-12 col-lg-4">
                <label for="id_last_name" class="form-label">Last Name</label>
                {{ form.last_name }}
              </div>
            </div>
            <div class="row">
              <div class="form-group col-12 col-lg-6">
                <label for="id_email" class="form-label">Email</label>
                {{ form.email }}
              </div>
              <div class="form-group col-12 col-lg-6">
                <label for="id_date_of_birth" class="form-label">Date of Birth</label>
                {{ form.date_of_birth }}
              </div>
            </div>
            <div class="row">
              <div class="form-group  col-12 col-lg-6">
                <label for="id_gender" class="form-label">Gender</label>
                {{ form.gender }}
              </div>
              <div class="form-group  col-12 col-lg-6">
                <label for="id_contact_number" class="form-label">Contact</label>
                {{ form.contact_number }}
              </div>
            </div>
            <div class="form-group">
              <label for="id_bio" class="form-label">Bio</label>
              {{ form.bio }}
            </div>
            <div class="row">
              <div class="form-group col-12 col-lg-4">
                <label for="id_city" class="form-label">City</label>
                {{ form.city }}
              </div>
              <div class="form-group col-12 col-lg-4">
                <label for="id_province" class="form-label">Province</label>
                {{ form.province }}
              </div>
              <div class="form-group col-12 col-lg-4">
                <label for="id_country" class="form-label">Country</label>
                {{ form.country }}
              </div>
            </div>
            <div class="form-group">
              <button type="submit" class="btn btn-primary">
                Save Changes
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock content %}

templates/pages/security.html
{% extends "base/base.html" %}

{% block title %} {{ title }} {% endblock %}

{% block content %}
<section class="section">
  <div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-header">
          <h5 class="card-title">Change Password</h5>
        </div>
        <div class="card-body">
          <form action="{% url 'security' %}" method="POST">
            {% csrf_token %}
            <div class="form-group my-2">
              <label for="id_old_password" class="form-label">Current Password</label>
              {{ form.old_password }}
              <div class="invalid-feedback" id="current-password-error">
                {% if form.errors %}
                  {% if form.old_password.errors %}
                    {% for error in form.old_password.errors %}
                      <p data-current-password-error="true">{{ error }}</p>
                    {% endfor %}
                  {% endif %}
                {% endif %}
              </div>          
            </div>
            <div class="form-group my-2">
              <label for="id_new_password1" class="form-label">New Password</label>
              {{ form.new_password1 }}
              <div class="invalid-feedback">
                {% if form.errors %}
                  {% if form.new_password2.errors %}
                    {% for error in form.new_password2.errors %}
                    <p>{{ error }}</p>
                    {% endfor %}
                  {% endif %}
                {% endif %}
              </div>
            </div>
            <div class="form-group my-2">
              <label for="id_new_password2" class="form-label">Confirm New Password</label>
              {{ form.new_password2 }}
              <div class="invalid-feedback" id="new-password-two-error">
                {% if form.errors %}
                  {% if form.new_password2.errors %}
                    {% for error in form.new_password2.errors %}
                      <p data-new-password-two-error="true">{{ error }}</p>
                    {% endfor %}
                  {% endif %}
                {% endif %}
              </div>  
            </div>

            <div class="form-group my-2 d-flex justify-content-end">
              <button type="submit" class="btn btn-primary">
                Save Changes
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock content %}

{% block extra_js %}
<script>
  $(function() {
    let current_password = $("#current-password-error p");
    let new_password2 = $("#new-password-two-error p");

    if (current_password.data("current-password-error")) {
      $("#id_old_password").addClass("is-invalid");
    }

    if (new_password2.data("new-password-two-error")) {
      $("#id_new_password1").addClass("is-invalid");
      $("#id_new_password2").addClass("is-invalid");
    }
  });
</script>
{% endblock extra_js %}