api/urls.py
from django.urls import path, include
from rest_framework import routers
from canvas.serializer import UserViewSet
from main.serializer import DepartmentViewSet, ProfileViewSet
from event.serializer import EventViewSet
from inbox.serializer import InboxViewSet
from dashboard.serializer import (
    ProfessorViewSet,
    CourseViewSet,
    EnrollmentViewSet,
    StudentViewSet,
)
from announcement.serializer import AnnouncementViewSet
from todo.serializer import TodoViewSet

router = routers.DefaultRouter()
router.register(r"users", UserViewSet)
router.register(r"departments", DepartmentViewSet)
router.register(r"profiles", ProfileViewSet)
router.register(r"events", EventViewSet)
router.register(r"inboxes", InboxViewSet)
router.register(r"professors", ProfessorViewSet)
router.register(r"courses", CourseViewSet)
router.register(r"enrollments", EnrollmentViewSet)
router.register(r"students", StudentViewSet)
router.register(r"announcements", AnnouncementViewSet)
router.register(r"todos", TodoViewSet)

urlpatterns = [
    path("", include(router.urls)),
]

canvas/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views


# Custom 400.html BAD REQUEST handler
handler400 = views.custom_400_view

# Custom 403.html PERMISSION DENIED handler
handler403 = views.custom_403_view

# Custom 404.html PAGE NOT FOUND handler
handler404 = views.custom_404_view

# Custom 500.html SERVER ERROR handler
handler500 = views.custom_500_view


urlpatterns = [
    path("", include("dashboard.urls")),
    path("grappelli/", include("grappelli.urls")),
    path("admin/", admin.site.urls),
    path("login/", views.LoginPageView.as_view(), name="login"),
    path("logout/", views.LogoutPageView.as_view(), name="logout"),
    path("profile/", views.ProfilePageView.as_view(), name="profile"),
    path("security/", views.SecurityPageView.as_view(), name="security"),
    path("api-auth/", include("rest_framework.urls"), name="rest_framework"),
    path("announcements/", include("announcement.urls")),
    path("grades/", include("grade.urls")),
    path("inbox/", include("inbox.urls")),
    path("event/", include("event.urls")),
    path("todo/", include("todo.urls")),
    path("api/", include("api.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/models.py
from django.db import models
from django.conf import settings


# Create your models here.
class Student(models.Model):
    ACADEMIC_STATUS_CHOICES = [
        ("Active", "Active"),
        ("On leave", "On leave"),
        ("Suspended", "Suspended"),
        ("Excused", "Excused"),
    ]

    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="student"
    )
    block = models.ForeignKey(
        "main.Block", on_delete=models.CASCADE, related_name="students"
    )
    department = models.ForeignKey(
        "main.Department",
        on_delete=models.CASCADE,
        related_name="students",
    )
    major = models.CharField(max_length=254)
    year = models.IntegerField()
    academic_status = models.CharField(
        max_length=254, choices=ACADEMIC_STATUS_CHOICES, default="Active"
    )
    is_graduated = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.user.username} - {self.department.name}"


class Professor(models.Model):
    ACADEMIC_RANK_CHOICES = [
        ("Professor", "Professor"),
        ("Assistant Professor", "Assistant Professor"),
        ("Associate Professor", "Associate Professor"),
        ("Full Professor", "Full Professor"),
    ]

    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="professor",
    )
    department = models.ForeignKey(
        "main.Department",
        on_delete=models.CASCADE,
        related_name="professors",
    )
    hire_date = models.DateTimeField()
    academic_rank = models.CharField(
        max_length=254, choices=ACADEMIC_RANK_CHOICES, default="Professor"
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.user.username} - {self.department.name}"


class Course(models.Model):
    DAYS_CHOICES = [
        ("MTH", "Monday and Thursday"),
        ("TF", "Tuesday and Friday"),
        ("WS", "Wednesday and Saturday"),
        ("M", "Monday"),
        ("T", "Tuesday"),
        ("W", "Wednesday"),
        ("TH", "Thursday"),
        ("F", "Friday"),
        ("S", "Saturday"),
        ("D", "Default"),
    ]

    professor = models.ForeignKey(
        Professor, on_delete=models.CASCADE, related_name="courses"
    )
    block = models.ForeignKey(
        "main.Block", on_delete=models.CASCADE, related_name="courses"
    )
    department = models.ForeignKey(
        "main.Department",
        on_delete=models.CASCADE,
        related_name="department",
    )
    semester = models.ForeignKey(
        "main.Semester", on_delete=models.CASCADE, related_name="semester"
    )
    title = models.CharField(max_length=254)
    code = models.CharField(max_length=6)
    codename = models.CharField(max_length=20)
    about = models.TextField(default="This is about course, populate it later")
    syllabus = models.TextField(default="This is syllabus course, populate it later")
    unit = models.IntegerField()
    start_time = models.TimeField(blank=True)
    end_time = models.TimeField(blank=True)
    days = models.CharField(max_length=20, choices=DAYS_CHOICES, default="D")
    room = models.CharField(max_length=20, default="undecided")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.professor.user.profile.first_name} | {self.code}:{self.codename} - {self.title}"

    class Meta:
        permissions = [
            ("change_about", "Can change the about course"),
            ("change_syllabus", "Can change the syllabus of the course"),
        ]


class Enrollment(models.Model):
    STATUS_CHOICES = [
        ("Enrolled", "Enrolled"),
        ("Withdrawn", "Withdrawn"),
        ("Dropped", "Dropped"),
    ]

    student = models.ForeignKey(
        Student, on_delete=models.CASCADE, related_name="enrollments"
    )
    course = models.ForeignKey(
        Course,
        on_delete=models.CASCADE,
        related_name="enrollments",
    )
    semester = models.ForeignKey(
        "main.Semester",
        on_delete=models.CASCADE,
        related_name="enrollments",
    )
    enrollment_date = models.DateTimeField()
    completion_date = models.DateTimeField()
    status = models.CharField(max_length=50, choices=STATUS_CHOICES)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class ModuleList(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name="modules")
    title = models.CharField(max_length=254, default="Week-")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.course.title} | Module List {self.title}"


class ModuleItem(models.Model):
    module_list = models.ForeignKey(
        ModuleList, on_delete=models.CASCADE, related_name="items"
    )
    title = models.CharField(max_length=254, default="Lesson 01")
    short_description = models.CharField(
        max_length=254, default="Learn the {your explanation about the course}!"
    )
    description = models.TextField(
        default="Put your description here about the module, and even content"
    )
    content_url = models.CharField(max_length=255, default="none")
    is_published = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.module_list.title} | Module {self.title}"

todo/models.py
from django.db import models
from django.conf import settings


# Create your models here.
class Todo(models.Model):
    course = models.ForeignKey(
        "dashboard.Course", on_delete=models.CASCADE, related_name="c_todos"
    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="todos"
    )
    title = models.CharField(max_length=254)
    description = models.TextField()
    due_date = models.DateTimeField()
    is_complete = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

dashboard/forms.py
from django import forms
from .models import Course, ModuleList, ModuleItem


class UpdateCourseAboutForm(forms.ModelForm):

    about = forms.CharField(
        widget=forms.Textarea(
            attrs={
                "type": "text",
                "class": "form-control d-none",
                "placeholder": "Update your 'About the Course' here...",
                # TODO: Remove value after testing
                "value": "Test value for About",
                "required": True,
            }
        ),
    )

    class Meta:
        model = Course
        fields = ["about"]


class UpdateCourseSyllabusForm(forms.ModelForm):

    syllabus = forms.CharField(
        widget=forms.Textarea(
            attrs={
                "type": "text",
                "class": "form-control d-none",
                "placeholder": "Update your 'syllabus' here...",
                # TODO: Remove value after testing
                "value": "Test value for syllabus",
                "required": True,
            }
        ),
    )

    class Meta:
        model = Course
        fields = ["syllabus"]


class UpdateModuleListForm(forms.ModelForm):
    class Meta:
        model = ModuleList
        fields = ["title"]


class UpdateModuleItemForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        module_item = kwargs.pop("module_item", "")

        super(UpdateModuleItemForm, self).__init__(*args, **kwargs)

        self.fields["title"] = forms.CharField(
            widget=forms.TextInput(
                attrs={"class": "form-control", "placeholder": module_item.title}
            )
        )
        self.fields["short_description"] = forms.CharField(
            widget=forms.TextInput(
                attrs={
                    "class": "form-control",
                    "placeholder": module_item.short_description,
                }
            )
        )
        self.fields["description"] = forms.CharField(
            widget=forms.Textarea(
                attrs={"class": "form-control", "placeholder": module_item.description}
            )
        )
        self.fields["content_url"] = forms.CharField(
            widget=forms.TextInput(
                attrs={"class": "form-control", "placeholder": module_item.content_url}
            )
        )
        self.fields["is_published"] = forms.CharField(
            widget=forms.CheckboxInput(attrs={"class": "form-check-input"}),
            required=False,
            initial=module_item.is_published,
        )

    class Meta:
        model = ModuleItem
        fields = [
            "title",
            "short_description",
            "description",
            "content_url",
            "is_published",
        ]

professor/templates/professor/pages/course.html
{% extends "base/base.html" %} 

{% load static %} 

{% block title %} {{ title }} {% endblock %} 

{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-2">
            <div class="d-block d-lg-none">
                <div class="position-relative w-100">
                    <button class="position-relative end-0 btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#sub-menu-collapse" aria-expanded="false" aria-controls="sub-menu-collapse">
                        Open Navigation
                    </button>
                </div>
                <div class="collapse" id="sub-menu-collapse">
                    <div class="list-group list-group-flush">
                        {% component "professor_sub_list" %}{% endcomponent %}
                    </div>
                </div>
            </div>
            <div class="list-group list-group-flush d-none d-lg-block">
                {% component "professor_sub_list" %}{% endcomponent %}
            </div>
        </div>
        <div class="col-lg-10">
        {% comment %} Content Here {% endcomment %}
            <div class="row">
                <div class="col-xs-1-12">
                    <div class="card">
                        <div class="card-body">
                            <h3 class="card-title">
                                <div class="hstack gap-3 d-flex justify-content-between">
                                    {{ object.title }} | {{ object.codename }} Course
                                    <a href="{% url 'professor:course-update-about' pk=object.id %}" class="btn btn-secondary">Edit</a>
                                </div>
                            </h3>
                            <p class="card-text">{{ object.semester.term }} Semester {{ object.semester.start_year }}-{{ object.semester.end_year }}</p>

                            <br />
                            <h3 class="text-bg-primary px-2 py-1 rounded-1">About your Professor</h3>
                            <br />

                            <h3 class="text-bg-primary px-2 py-1 rounded-1">About this Course</h3>
                            <p class="text-justify lh-base">
                                {% autoescape off %}
                                    {{ object.about }}
                                {% endautoescape %}
                            </p>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

professor/templates/professor/pages/course_announcement.html
{% extends "base/base.html" %} 

{% load static %} 

{% block title %} {{ title }} {% endblock %} 

{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-2">
            <div class="d-block d-lg-none">
                <div class="position-relative w-100">
                    <button class="position-relative end-0 btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#sub-menu-collapse" aria-expanded="false" aria-controls="sub-menu-collapse">
                        Open Navigation
                    </button>
                </div>
                <div class="collapse" id="sub-menu-collapse">
                    <div class="list-group list-group-flush">
                        {% component "professor_sub_list" %}{% endcomponent %}
                    </div>
                </div>
            </div>
            <div class="list-group list-group-flush d-none d-lg-block">
                {% component "professor_sub_list" %}{% endcomponent %}
            </div>
        </div>
        <div class="col-lg-10">
        {% comment %} Content Here {% endcomment %}
        <div class="row">
          <div class="col-xs-1-12">
            <div class="card">
              <div class="card-body">
                <h3 class="card-title">Announcements</h3>
              </div>
            </div>
          </div>
        </div>
        </div>
    </div>
</div>
{% endblock content %}

professor/templates/professor/pages/course_assignment.html
{% extends "base/base.html" %} 

{% load static %} 

{% block title %} {{ title }} {% endblock %} 

{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-2">
            <div class="d-block d-lg-none">
                <div class="position-relative w-100">
                    <button class="position-relative end-0 btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#sub-menu-collapse" aria-expanded="false" aria-controls="sub-menu-collapse">
                        Open Navigation
                    </button>
                </div>
                <div class="collapse" id="sub-menu-collapse">
                    <div class="list-group list-group-flush">
                        {% component "professor_sub_list" %}{% endcomponent %}
                    </div>
                </div>
            </div>
            <div class="list-group list-group-flush d-none d-lg-block">
                {% component "professor_sub_list" %}{% endcomponent %}
            </div>
        </div>
        <div class="col-lg-10">
        {% comment %} Content Here {% endcomment %}
        <div class="row">
          <div class="col-xs-1-12">
            <div class="card">
              <div class="card-body">
                <h3 class="card-title">Assignments</h3>
              </div>
            </div>
          </div>
        </div>
        </div>
    </div>
</div>
{% endblock content %}

professor/templates/professor/pages/course_create_module.html
{% extends "base/base.html" %} 

{% load static %} 

{% block title %} {{ title }} {% endblock %} 

{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-2">
            <div class="d-block d-lg-none">
                <div class="position-relative w-100">
                    <button class="position-relative end-0 btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#sub-menu-collapse" aria-expanded="false" aria-controls="sub-menu-collapse">
                        Open Navigation
                    </button>
                </div>
                <div class="collapse" id="sub-menu-collapse">
                    <div class="list-group list-group-flush">
                        {% component "professor_sub_list" %}{% endcomponent %}
                    </div>
                </div>
            </div>
            <div class="list-group list-group-flush d-none d-lg-block">
                {% component "professor_sub_list" %}{% endcomponent %}
            </div>
        </div>
        <div class="col-lg-10">
        {% comment %} Content Here {% endcomment %}
            <div class="row">
                <div class="col-xs-1-12">
                    <div class="card">
                        <div class="card-body">
                            <h3 class="card-title">
                                <div class="hstack gap-3 d-flex justify-content-between">
                                    Create a module
                                </div>
                            </h3>
                            <p class="card-text">Create and manage your course module</p>

                            <br />

                            <form>
                                {% csrf_token %}

                                {{ form }}

                                <button class="btn btn-primary" type="submit">Create module</button>
                            </form>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

professor/templates/professor/pages/course_module.html
{% extends "base/base.html" %} 

{% load static %} 

{% block title %} {{ title }} {% endblock %} 

{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-2">
            <div class="d-block d-lg-none">
                <div class="position-relative w-100">
                    <button class="position-relative end-0 btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#sub-menu-collapse" aria-expanded="false" aria-controls="sub-menu-collapse">
                        Open Navigation
                    </button>
                </div>
                <div class="collapse" id="sub-menu-collapse">
                    <div class="list-group list-group-flush">
                        {% component "professor_sub_list" %}{% endcomponent %}
                    </div>
                </div>
            </div>
            <div class="list-group list-group-flush d-none d-lg-block">
                {% component "professor_sub_list" %}{% endcomponent %}
            </div>
        </div>
        <div class="col-lg-10">
        {% comment %} Content Here {% endcomment %}
            <div class="row">
                <div class="col-xs-1-12">
                    <div class="card">
                        <div class="card-body">
                            <h3 class="card-title">
                                <div class="hstack gap-3 d-flex justify-content-between">
                                    Modules
                                    <a href="{% url 'professor:course-create-module' pk=object.id %}" class="btn btn-success">
                                        <i class="fa fa-plus"></i> Add new module/s
                                    </a>
                                </div>
                            </h3>
                            <p class="card-text">Manage your modules here!</p>
                            <div class="d-flex flex-column gap-3">
                                {% component "module_list" %}{% endcomponent %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

professor/templates/professor/pages/course_syllabus.html
{% extends "base/base.html" %} 

{% load static %} 

{% block title %} {{ title }} {% endblock %} 

{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-2">
            <div class="d-block d-lg-none">
                <div class="position-relative w-100">
                    <button class="position-relative end-0 btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#sub-menu-collapse" aria-expanded="false" aria-controls="sub-menu-collapse">
                        Open Navigation
                    </button>
                </div>
                <div class="collapse" id="sub-menu-collapse">
                    <div class="list-group list-group-flush">
                        {% component "professor_sub_list" %}{% endcomponent %}
                    </div>
                </div>
            </div>
            <div class="list-group list-group-flush d-none d-lg-block">
                {% component "professor_sub_list" %}{% endcomponent %}
            </div>
        </div>
        <div class="col-lg-10">
        {% comment %} Content Here {% endcomment %}
        <div class="row">
          <div class="col-xs-1-12">
            <div class="card">
              <div class="card-body">
                <h3 class="card-title">
                    <div class="hstack gap-3 d-flex justify-content-between">
                        Syllabus
                        <a href="{% url 'professor:course-update-syllabus' pk=object.id %}" class="btn btn-secondary">Edit</a>
                    </div>
                </h3>

                <br />
                <p class="text-justify lh-base">{{ object.syllabus }}</p>
              </div>
            </div>
          </div>
        </div>
        </div>
    </div>
</div>
{% endblock content %}

professor/templates/professor/pages/course_update_home.html
{% extends "base/base.html" %} 

{% load static %} 

{% block title %} {{ title }} {% endblock %} 

{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-12">
        {% comment %} Content Here {% endcomment %}
        <div class="row">
          <div class="col-xs-1-12">
            <div class="card">
              <div class="card-body">
                <h3 class="card-title">Updating {{ object.title }} | {{ object.codename }} 'About the Course'</h3>
                <p class="card-text">Accepts HTML and Markdown</p>
                <br />


                {% if form_success %}
                <div class="alert alert-success alert-dismissible show fade">
                    <span class="fs-5"><i class="bi bi-check-circle"></i> Success Updating About the Course Content!<span>
                    <a href="{% url 'professor:course' pk=object.id %}">Go back?</a>
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% endif %}


                <form method="POST" action="{% url 'professor:course-update-about' pk=object.id %}">
                    {% csrf_token %}
                    {{ form.about }}
                    <div id="editor"></div>
                    <br />
                    <button class="btn btn-primary" type="submit">Save Changes</button>
                </form>
              </div>
            </div>
          </div>
        </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block extra_js %}
<script>
  let about_textarea = $("#id_about");

  let quill = new Quill('#editor', {
    theme: 'snow'
  });

  console.log(quill)

  quill.on('text-change', (delta, oldDelta, source) => {
    console.log(quill.getContents())
  });

  about_textarea.val(about_textarea.attr("value"));
</script>
{% endblock extra_js %}

professor/templates/professor/pages/course_update_module.html
{% extends "base/base.html" %} 

{% load static %} 

{% block title %} {{ title }} {% endblock %} 

{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-2">
            <div class="d-block d-lg-none">
                <div class="position-relative w-100">
                    <button class="position-relative end-0 btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#sub-menu-collapse" aria-expanded="false" aria-controls="sub-menu-collapse">
                        Open Navigation
                    </button>
                </div>
                <div class="collapse" id="sub-menu-collapse">
                    <div class="list-group list-group-flush">
                        {% component "professor_sub_list" %}{% endcomponent %}
                    </div>
                </div>
            </div>
            <div class="list-group list-group-flush d-none d-lg-block">
                {% component "professor_sub_list" %}{% endcomponent %}
            </div>
        </div>
        <div class="col-lg-10">
        {% comment %} Content Here {% endcomment %}
            <div class="row">
                <div class="col-xs-1-12">
                    <div class="card">
                        <div class="card-body">
                            <h3 class="card-title">
                                <div class="hstack gap-3 d-flex justify-content-between">
                                    Update {{ module_item.title }}
                                </div>
                            </h3>

                            <br/>

                            {% if form_success %}
                            <div class="alert alert-success alert-dismissible show fade">
                                <span class="fs-5"><i class="bi bi-check-circle"></i> Success Updating Syllabus Content!<span>
                                <a href="{% url 'professor:course-view-module' pk=object.id item_id=module_item.id %}">Go back?</a>
                                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                            </div>
                            {% endif %}

                            <form method="post">
                                {% csrf_token %}
                                <div class="form-group">
                                    <label for="id_title" class="form-label">Title</label>
                                    {{ form.title }}
                                </div>
                                <div class="form-group">
                                    <label for="id_short_description" class="form-label">Short Description</label>
                                    {{ form.short_description }}
                                </div>
                                <div class="form-group">
                                    <label for="id_description" class="form-label">Description</label>
                                    {{ form.description }}
                                </div>
                                <div class="form-group">
                                    <label for="id_content_url" class="form-label">Content Url</label>
                                    {{ form.content_url }}
                                </div>
                                <div class="form-group">
                                    {{ form.is_published }}
                                    <label for="id_is_published" class="form-label">Is Publish</label>
                                </div>
                                <div class="form-group">
                                    <button type="submit" class="btn btn-primary">
                                        Save Changes
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

professor/templates/professor/pages/course_update_syllabus.html
{% extends "base/base.html" %} 

{% load static %} 

{% block title %} {{ title }} {% endblock %} 

{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-12">
        {% comment %} Content Here {% endcomment %}
        <div class="row">
          <div class="col-xs-1-12">
            <div class="card">
              <div class="card-body">
                <h3 class="card-title">Updating Syllabus</h3>
                <p class="card-text">Accepts HTML and Markdown</p>
                <br />


                {% if form_success %}
                <div class="alert alert-success alert-dismissible show fade">
                    <span class="fs-5"><i class="bi bi-check-circle"></i> Success Updating Syllabus Content!<span>
                    <a href="{% url 'professor:course-syllabus' pk=object.id %}">Go back?</a>
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% endif %}


                <form method="POST" action="{% url 'professor:course-update-syllabus' pk=object.id %}">
                    {% csrf_token %}
                    {{ form.syllabus }}
                    <div id="editor"></div>
                    <br />
                    <button class="btn btn-primary" type="submit">Save Changes</button>
                </form>
              </div>
            </div>
          </div>
        </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block extra_js %}
<script>
  let about_textarea = $("#id_syllabus");

  let quill = new Quill('#editor', {
    theme: 'snow'
  });

  console.log(quill)

  quill.on('text-change', (delta, oldDelta, source) => {
    console.log(quill.getContents())
  });

  about_textarea.val(about_textarea.attr("value"));
</script>
{% endblock extra_js %}