api/urls.py
from django.urls import path, include
from rest_framework import routers
from canvas.serializer import UserViewSet
from main.serializer import DepartmentViewSet, ProfileViewSet
from event.serializer import EventViewSet
from inbox.serializer import InboxViewSet
from dashboard.serializer import (
    ProfessorViewSet,
    CourseViewSet,
    EnrollmentViewSet,
    StudentViewSet,
)
from announcement.serializer import AnnouncementViewSet
from todo.serializer import TodoViewSet

router = routers.DefaultRouter()
router.register(r"users", UserViewSet)
router.register(r"departments", DepartmentViewSet)
router.register(r"profiles", ProfileViewSet)
router.register(r"events", EventViewSet)
router.register(r"inboxes", InboxViewSet)
router.register(r"professors", ProfessorViewSet)
router.register(r"courses", CourseViewSet)
router.register(r"enrollments", EnrollmentViewSet)
router.register(r"students", StudentViewSet)
router.register(r"announcements", AnnouncementViewSet)
router.register(r"todos", TodoViewSet)

urlpatterns = [
    path("", include(router.urls)),
]

canvas/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views


# Custom 400.html BAD REQUEST handler
handler400 = views.custom_400_view

# Custom 403.html PERMISSION DENIED handler
handler403 = views.custom_403_view

# Custom 404.html PAGE NOT FOUND handler
handler404 = views.custom_404_view

# Custom 500.html SERVER ERROR handler
handler500 = views.custom_500_view


urlpatterns = [
    path("", include("dashboard.urls")),
    path("grappelli/", include("grappelli.urls")),
    path("admin/", admin.site.urls),
    path("login/", views.LoginPageView.as_view(), name="login"),
    path("logout/", views.LogoutPageView.as_view(), name="logout"),
    path("profile/", views.ProfilePageView.as_view(), name="profile"),
    path("security/", views.SecurityPageView.as_view(), name="security"),
    path("api-auth/", include("rest_framework.urls"), name="rest_framework"),
    path("announcements/", include("announcement.urls")),
    path("grades/", include("grade.urls")),
    path("inbox/", include("inbox.urls")),
    path("event/", include("event.urls")),
    path("todo/", include("todo.urls")),
    path("api/", include("api.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

inbox/urls.py
from django.urls import path
from . import views

app_name = "inbox"

urlpatterns = [
    path("", views.InboxList.as_view(), name="inbox"),
    path("compose/", views.InboxCompose.as_view(), name="inbox-compose"),
]

inbox/models.py
from django.db import models
from django.conf import settings


# Create your models here.
class Inbox(models.Model):
    sender = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="sender"
    )
    receiver = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="receiver"
    )
    is_starred = models.BooleanField(default=False)
    subject = models.CharField(max_length=254)
    content = models.TextField()
    is_archived = models.BooleanField(default=False)
    is_read = models.BooleanField(default=False)
    sent_at = models.DateTimeField()
    read_at = models.DateTimeField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

inbox/views.py
from urllib.parse import urlencode
from enum import Enum
from common.util.views import View
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic import TemplateView


class InboxType(Enum):
    ALL = "all"
    SENT = "sent"
    STARRED = "starred"
    TRASH = "trash"


# Create your views here.
class InboxList(View, TemplateView):
    template_name = "inbox/list.html"

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)

        context["title"] = "Inbox"
        context["link"] = "inbox"

        return context

    def get_inbox_query_params(self, request):
        query_params = {}

        try:
            query_params["type"] = request.GET["type"]
            query_params["page"] = request.GET["page"]
        except:
            return None

        return query_params

    def get_inbox_list(self, request, query_params):
        inbox_list = []
        page = query_params["page"]

        if query_params["type"] == InboxType.ALL:
            inbox_list = self.get_inbox_list_all(request, page)
        elif query_params["type"] == InboxType.SENT:
            inbox_list = self.get_inbox_list_sent(request, page)
        elif query_params["type"] == InboxType.STARRED:
            inbox_list = self.get_inbox_list_starred(request, page)
        elif query_params["type"] == InboxType.TRASH:
            inbox_list = self.get_inbox_list_trash(request, page)
        else:
            return False

        return inbox_list

    def get_inbox_list_all(self, request, page):
        return True

    def get_inbox_list_sent(self, request, page):
        return True

    def get_inbox_list_starred(self, request, page):
        return True

    def get_inbox_list_trash(self, request, page):
        return True

    def get(self, request, *args, **kwargs):

        context = self.get_context_data(*args, **kwargs)

        default_query_params = {"type": "all", "page": 1}

        query_params = self.get_inbox_query_params(request)

        print("Default query params", default_query_params)
        print("Query params", query_params["type"])

        if query_params is None:
            return redirect(
                reverse("inbox:inbox") + f"?{urlencode(default_query_params)}"
            )

        inbox_list = self.get_inbox_list(request, query_params)

        context["type"] = query_params["type"]
        context["page"] = int(query_params["page"])
        context["page_from"] = (int(query_params["page"]) * 10) - 9
        context["page_to"] = int(query_params["page"]) * 10
        context["inboxes"] = inbox_list

        return render(request, self.template_name, context)


class InboxCompose(View, TemplateView):
    template_name = "inbox/list.html"

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)

        context["title"] = "Compose"
        context["link"] = "inbox"

        return context

    def get(self, request, *args, **kwargs):

        context = self.get_context_data(*args, **kwargs)

        return render(request, self.template_name, context)

inbox/templates/inbox/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="{% static '/favicon.ico' %}">

        <title>{% block title %} Title Here! {% endblock %} | Canvas++</title>

        <!-- Main styling starts here -->
        <link rel="stylesheet" crossorigin href="{% static '/css/application-email.min.css' %}"/> 
        
        <link rel="stylesheet" crossorigin href="{% static '/css/bootstrap.css' %}"/>
        
        <link rel="stylesheet" crossorigin href="{% static '/css/bootstrap-dark.css' %}"/>

        <link rel="stylesheet" href="{% static '/css/fontawesome-free.min.css' %}"/>

        <link rel="stylesheet" crossorigin href="{% static '/css/iconly.min.css' %}"/>

        <link rel="stylesheet" crossorigin href="{% static '/css/table-datatable-jquery.min.css' %}"/>

        {% comment %} TODO: Minify the stylesheet {% endcomment %}
        <link rel="stylesheet" crossorigin href="{% static '/css/toastify.css' %}"/>

        <link rel="stylesheet" crossorigin href="{% static '/css/sweetalert2.min.css' %}"/>

        {% comment %} TODO: Minify the stylesheet {% endcomment %}
        <link rel="stylesheet" crossorigin href="{% static '/css/dataTables.bootstrap5.css' %}"/>

        <link rel="stylesheet" crossorigin href="{% static '/css/quill.core.css' %}"/>
        <link rel="stylesheet" crossorigin href="{% static '/css/quill.snow.css' %}"/>


        {% component_css_dependencies %}

        {% block extra_css %}{% endblock extra_css %}

        <!-- Main styling ends here -->
    </head>
    <body>
        <!-- Dark Mode Javascript -->
        <script src="{% static './js/initTheme.js' %}"></script>

        <!-- Main page starts here -->
        <div id="app">

            {% block nav %}
            {% component "nav" %}{% endcomponent %}
            {% endblock nav %}
            {% block sidebar %}
            {% component "sidebar" %}{% endcomponent %}
            {% endblock sidebar %}

        <div id="main">
            <div class="page-heading email-application overflow-hidden">
                <section class="section content-area-wrapper">
                    <div class="sidebar-left">
                        <div class="sidebar">
                            <div class="sidebar-content email-app-sidebar d-flex">
                            <!-- sidebar close icon -->
                            <span class="sidebar-close-icon">
                                <i class="bi bi-x"></i>
                            </span>
                            <!-- sidebar close icon -->
                            <div class="email-app-menu">
                                <div class="form-group form-group-compose">
                                <!-- compose button  -->
                                <a
                                    type="button"
                                    href="{% url 'inbox:inbox-compose' %}"
                                    class="btn btn-primary btn-block my-4 compose-btn"
                                >
                                    <i class="bi bi-plus"></i>
                                    Compose
                                </a>
                                </div>
                                <div class="sidebar-menu-list ps">
                                <!-- sidebar menu  -->
                                {% include "inbox/section/sidebar-menu.html" %}
                                <!-- sidebar menu  end-->
                    
                                <!-- sidebar label end -->
                                <div class="ps__rail-x" style="left: 0px; bottom: 0px">
                                    <div
                                    class="ps__thumb-x"
                                    tabindex="0"
                                    style="left: 0px; width: 0px"
                                    ></div>
                                </div>
                                <div class="ps__rail-y" style="top: 0px; right: 0px">
                                    <div
                                    class="ps__thumb-y"
                                    tabindex="0"
                                    style="top: 0px; height: 0px"
                                    ></div>
                                </div>
                                </div>
                            </div>
                            </div>
                        </div>
                    </div>
                    <div class="content-right">
                        <div class="content-overlay"></div>
                        <div class="content-wrapper">
                            <div class="content-header row"></div>
                        <div class="content-body">
                        <!-- email app overlay -->
                        <div class="app-content-overlay"></div>
                            <div class="email-app-area">
                                <!-- Email list Area -->
                                <div class="email-app-list-wrapper">
                                <div class="email-app-list">
                                    <div class="email-action">

                                        {% include "inbox/section/action.html" %}

                                    <!-- email user list start -->
                                    <div class="email-user-list list-group ps ps--active-y">
                                    {% include "inbox/section/mail-list.html" %}
                                    <!-- email user list end -->
                                    </div>
                                </div>
                                </div>
                                <!--/ Email list Area -->
                    
                            </div>
                        </div>
                    </div>
                    </div>
                </section>
            </div>
        </div>
        </div>
        <!-- Main page ends here -->

        {% comment %} Messages display starts here (hidden by default for toastify to use) {% endcomment %}
        {% if messages %}
        <ul class="messages d-none">
        {% for message in messages %}
            <li data-message="{{ message }}" data-level={{ message.level }}>
            </li>
        {% endfor %}
        </ul>
        {% endif %}
        {% comment %} Messages display ends here {% endcomment %}

        {% comment %} <Main Sources {% endcomment %}

        {% comment %} Handling dark mode toggle {% endcomment %}
        <script src="{% static '/js/dark.js' %}" defer></script>
        {% comment %} Handling dark mode toggle {% endcomment %}

        {% comment %} App's script starts here {% endcomment %}
        <script src="{% static '/js/app.js' %}" defer></script>
        {% comment %} App's script starts here {% endcomment %}

        {% comment %} Custom scrollbar starts here {% endcomment %}
        <script src="{% static '/js/perfect-scrollbar.min.js' %}" defer></script>
        {% comment %} Custom scrollbar starts here {% endcomment %}

        {% comment %} jQuery starts here {% endcomment %}
        <script src="{% static '/js/jquery.min.js' defer %}"></script>
        {% comment %} jQuery ends here {% endcomment %}

        {% comment %} Toastify.js starts here {% endcomment %}
        <script src="{% static '/js/toastify.js' %}" defer></script>
        <script src="{% static '/js/display-toastify.js' %}" defer></script>
        {% comment %} Toastify.js ends here {% endcomment %}

        {% comment %} SweetAlert starts here {% endcomment %}
        <script src="{% static '/js/sweetalert2.min.js' %}"></script>
        {% comment %} SweetAlert ends here {% endcomment %}

        {% comment %} Jquery DataTables with BS5 starts here {% endcomment %}
        <script src="{% static '/js/jquery.dataTables.min.js' %}" defer></script>
        <script src="{% static '/js/dataTables.bootstrap5.min.js' %}" defer></script>
        {% comment %} Jquery DataTables with BS5 ends here {% endcomment %}

        <script src="{% static '/js/quill.min.js' %}"></script>

        {% component_js_dependencies %}

        {% block extra_js %}

        {% endblock extra_js %}
    </body>
</html>

inbox/templates/inbox/create.html
{% extends "base/base.html" %} 

{% load static %} 

{% block title %} {{ title }} {% endblock %} 

{% block extra_css %}

{% endblock extra_css %}

{% block content %}
{% endblock content %}

{% block extra_js %}{% endblock extra_js %}

inbox/templates/inbox/detail.html
{% extends "base/base.html" %} 

{% load static %} 

{% block title %} {{ title }} {% endblock %} 

{% block extra_css %}

{% endblock extra_css %}

{% block content %}
{% endblock content %}

{% block extra_js %}{% endblock extra_js %}

inbox/templates/inbox/list.html
{% extends "inbox/base.html" %} 

{% load static %} 

{% block title %} {{ title }} {% endblock %} 

{% block extra_css %}

{% endblock extra_css %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-12">
        {% comment %} Content Here {% endcomment %}
            <div class="row">
                <div class="col-xs-1-12">
                    <div class="card">
                        <div class="card-body">
                            <h3 class="card-title">
                                <div class="hstack gap-3 d-flex justify-content-between">
                                    Inbox List
                                </div>
                            </h3>

                            <br />

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block extra_js %}{% endblock extra_js %}

inbox/templates/inbox/update.html
{% extends "base/base.html" %} 

{% load static %} 

{% block title %} {{ title }} {% endblock %} 

{% block extra_css %}

{% endblock extra_css %}

{% block content %}
{% endblock content %}

{% block extra_js %}{% endblock extra_js %}