api/urls.py
from django.urls import path, include
from rest_framework import routers
from canvas.serializer import UserViewSet
from main.serializer import DepartmentViewSet, ProfileViewSet
from event.serializer import EventViewSet
from inbox.serializer import InboxViewSet
from dashboard.serializer import (
    ProfessorViewSet,
    CourseViewSet,
    EnrollmentViewSet,
    StudentViewSet,
)
from announcement.serializer import AnnouncementViewSet
from todo.serializer import TodoViewSet

router = routers.DefaultRouter()
router.register(r"users", UserViewSet)
router.register(r"departments", DepartmentViewSet)
router.register(r"profiles", ProfileViewSet)
router.register(r"events", EventViewSet)
router.register(r"inboxes", InboxViewSet)
router.register(r"professors", ProfessorViewSet)
router.register(r"courses", CourseViewSet)
router.register(r"enrollments", EnrollmentViewSet)
router.register(r"students", StudentViewSet)
router.register(r"announcements", AnnouncementViewSet)
router.register(r"todos", TodoViewSet)

urlpatterns = [
    path("", include(router.urls)),
]

canvas/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views


# Custom 400.html BAD REQUEST handler
handler400 = views.custom_400_view

# Custom 403.html PERMISSION DENIED handler
handler403 = views.custom_403_view

# Custom 404.html PAGE NOT FOUND handler
handler404 = views.custom_404_view

# Custom 500.html SERVER ERROR handler
handler500 = views.custom_500_view


urlpatterns = [
    path("", include("dashboard.urls")),
    path("grappelli/", include("grappelli.urls")),
    path("admin/", admin.site.urls),
    path("login/", views.LoginPageView.as_view(), name="login"),
    path("logout/", views.LogoutPageView.as_view(), name="logout"),
    path("profile/", views.ProfilePageView.as_view(), name="profile"),
    path("security/", views.SecurityPageView.as_view(), name="security"),
    path("api-auth/", include("rest_framework.urls"), name="rest_framework"),
    path("announcements/", include("announcement.urls")),
    path("grades/", include("grade.urls")),
    path("inbox/", include("inbox.urls")),
    path("event/", include("event.urls")),
    path("todo/", include("todo.urls")),
    path("api/", include("api.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/urls.py
from django.urls import path
from .views.announcement import Announcement, AnnouncementDetail
from .views.assignment import Assignment
from .views.views import Dashboard
from .views.home import Home, HomeUpdate
from .views.syllabus import Syllabus
from .views.people import PeopleList
from .views.module import Module, ModuleDetail


app_name = "dashboard"

homeurls = [
    path("course/<int:course_id>/home/", Home.as_view(), name="course-home"),
    path(
        "course/<int:course_id>/home/update/",
        HomeUpdate.as_view(),
        name="course-home-update",
    ),
]

syllabusurls = [
    path(
        "course/<int:course_id>/syllabus/", Syllabus.as_view(), name="course-syllabus"
    ),
]

peopleurls = [
    path("course/<int:course_id>/people/", PeopleList.as_view(), name="course-people")
]

announcementurls = [
    path(
        "course/<int:course_id>/announcements/",
        Announcement.as_view(),
        name="course-announcement",
    ),
    path(
        "course/<int:course_id>/announcements/<int:announcement_id>",
        AnnouncementDetail.as_view(),
        name="course-announcement-detail",
    ),
]

moduleurls = [
    path("course/<int:course_id>/modules/", Module.as_view(), name="course-module"),
    path(
        "course/<int:course_id>/modules/<int:module_id>/",
        ModuleDetail.as_view(),
        name="course-module-detail",
    ),
]

assignmenturls = [
    path(
        "course/<int:course_id>/assignments/",
        Assignment.as_view(),
        name="course-assignment",
    ),
]

urlpatterns = [
    path("", Dashboard.as_view(), name="dashboard"),
]


# adding home to urlpattern
urlpatterns += homeurls

# adding syllabus to urlpattern
urlpatterns += syllabusurls

# adding people to urlpattern
urlpatterns += peopleurls

# adding announcement to urlpattern
urlpatterns += announcementurls

# adding module to urlpattern
urlpatterns += moduleurls

# adding assignment to urlpattern
urlpatterns += assignmenturls

dashboard/models.py
from django.db import models
from django.conf import settings


# Create your models here.
class Student(models.Model):
    ACADEMIC_STATUS_CHOICES = [
        ("Active", "Active"),
        ("On leave", "On leave"),
        ("Suspended", "Suspended"),
        ("Excused", "Excused"),
    ]

    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="student"
    )
    block = models.ForeignKey(
        "main.Block", on_delete=models.CASCADE, related_name="students"
    )
    department = models.ForeignKey(
        "main.Department",
        on_delete=models.CASCADE,
        related_name="students",
    )
    major = models.CharField(max_length=254)
    year = models.IntegerField()
    academic_status = models.CharField(
        max_length=254, choices=ACADEMIC_STATUS_CHOICES, default="Active"
    )
    is_graduated = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.user.username} - {self.department.name}"


class Professor(models.Model):
    ACADEMIC_RANK_CHOICES = [
        ("Professor", "Professor"),
        ("Assistant Professor", "Assistant Professor"),
        ("Associate Professor", "Associate Professor"),
        ("Full Professor", "Full Professor"),
    ]

    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="professor",
    )
    department = models.ForeignKey(
        "main.Department",
        on_delete=models.CASCADE,
        related_name="professors",
    )
    hire_date = models.DateTimeField()
    academic_rank = models.CharField(
        max_length=254, choices=ACADEMIC_RANK_CHOICES, default="Professor"
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.user.username} - {self.department.name}"


class Course(models.Model):
    DAYS_CHOICES = [
        ("MTH", "Monday and Thursday"),
        ("TF", "Tuesday and Friday"),
        ("WS", "Wednesday and Saturday"),
        ("M", "Monday"),
        ("T", "Tuesday"),
        ("W", "Wednesday"),
        ("TH", "Thursday"),
        ("F", "Friday"),
        ("S", "Saturday"),
        ("D", "Default"),
    ]

    professor = models.ForeignKey(
        Professor, on_delete=models.CASCADE, related_name="courses"
    )
    block = models.ForeignKey(
        "main.Block", on_delete=models.CASCADE, related_name="courses"
    )
    department = models.ForeignKey(
        "main.Department",
        on_delete=models.CASCADE,
        related_name="department",
    )
    semester = models.ForeignKey(
        "main.Semester", on_delete=models.CASCADE, related_name="semester"
    )
    title = models.CharField(max_length=254)
    code = models.CharField(max_length=6)
    codename = models.CharField(max_length=20)
    about = models.TextField(default="This is about course, populate it later")
    syllabus = models.TextField(default="This is syllabus course, populate it later")
    unit = models.IntegerField()
    start_time = models.TimeField(blank=True)
    end_time = models.TimeField(blank=True)
    days = models.CharField(max_length=20, choices=DAYS_CHOICES, default="D")
    room = models.CharField(max_length=20, default="undecided")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.professor.user.profile.first_name} | {self.code}:{self.codename} - {self.title}"

    class Meta:
        permissions = [
            ("change_about", "Can change the about course"),
            ("change_syllabus", "Can change the syllabus of the course"),
        ]


class Enrollment(models.Model):
    STATUS_CHOICES = [
        ("Enrolled", "Enrolled"),
        ("Withdrawn", "Withdrawn"),
        ("Dropped", "Dropped"),
    ]

    student = models.ForeignKey(
        Student, on_delete=models.CASCADE, related_name="enrollments"
    )
    course = models.ForeignKey(
        Course,
        on_delete=models.CASCADE,
        related_name="enrollments",
    )
    semester = models.ForeignKey(
        "main.Semester",
        on_delete=models.CASCADE,
        related_name="enrollments",
    )
    enrollment_date = models.DateTimeField()
    completion_date = models.DateTimeField()
    status = models.CharField(max_length=50, choices=STATUS_CHOICES)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class ModuleList(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name="modules")
    title = models.CharField(max_length=254, default="Week-")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.course.title} | Module List {self.title}"


class ModuleItem(models.Model):
    module_list = models.ForeignKey(
        ModuleList, on_delete=models.CASCADE, related_name="items"
    )
    title = models.CharField(max_length=254, default="Lesson 01")
    short_description = models.CharField(
        max_length=254, default="Learn the {your explanation about the course}!"
    )
    description = models.TextField(
        default="Put your description here about the module, and even content"
    )
    content_url = models.CharField(max_length=255, default="none")
    is_published = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.module_list.title} | Module {self.title}"

dashboard/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from common.util.get_courses import get_professor_courses


class View(LoginRequiredMixin, TemplateView):
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        user = self.request.user

        # TODO: Add logic for processing courses both professor and student
        # TODO: Add logic to cache and store the courses generated to request.session
        courses = get_professor_courses(user)

        context["courses"] = courses
        return context


class Dashboard(View):
    template_name = "dashboard/index.html"

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, self.get_context_data())

dashboard/views/announcement.py
from django.shortcuts import render

from dashboard.util.view import DashboardParentView


class Announcement(DashboardParentView):
    template_name = "dashboard/announcement/list.html"

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)

        context["title"] = f"{context['title']} Announcements"
        context["sub_link"] = "announcement"

        return context

    def get(self, request, *args, **kwargs):

        context = self.get_context_data(*args, **kwargs)

        return render(request, self.template_name, context)


class AnnouncementDetail(DashboardParentView):
    template_name = "dashboard/announcement/detail.html"

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)

        context["title"] = f"{context['title']} Announcements"
        context["sub_link"] = "announcement"

        return context

    def get(self, request, *args, **kwargs):

        context = self.get_context_data(*args, **kwargs)

        return render(request, self.template_name, context)

dashboard/views/assignment.py
from django.shortcuts import render

from dashboard.util.view import DashboardParentView


class Assignment(DashboardParentView):
    template_name = "dashboard/assignment/list.html"

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)

        context["title"] = f"{context['title']} Assignments"
        context["sub_link"] = "assignment"

        return context

    def get(self, request, *args, **kwargs):

        context = self.get_context_data(*args, **kwargs)

        return render(request, self.template_name, context)

dashboard/views/home.py
from django.shortcuts import render

from dashboard.util.view import DashboardParentView

from dashboard.forms.home.update import HomeUpdateForm


class Home(DashboardParentView):
    template_name = "dashboard/home/detail.html"

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)

        context["title"] = f"{context['title']} Home"
        context["sub_link"] = "home"

        return context

    def get(self, request, *args, **kwargs):

        context = self.get_context_data(*args, **kwargs)

        return render(request, self.template_name, context)


class HomeUpdate(DashboardParentView):
    template_name = "dashboard/home/update.html"

    permission_denied_message = "You're not allowed to view and edit this course about!"

    def __init__(self):
        permissions = ["dashboard.change_about"]
        self.permission_required = self.override_permissions_required(
            permissions=permissions
        )

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)

        context["title"] = f"Update {context['title']} About"
        context["sub_link"] = "home"

        return context

    def get(self, request, *args, **kwargs):

        context = self.get_context_data(*args, **kwargs)

        context["form"] = HomeUpdateForm()

        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):

        context = self.get_context_data(*args, **kwargs)

        form = HomeUpdateForm(data=request.POST)

        if form.is_valid():
            print("The content is")
            print(form.cleaned_data["content"])
        else:
            print("Not valid!")

        return render(request, self.template_name, context)

dashboard/views/module.py
from django.shortcuts import render, get_object_or_404

from dashboard.util.view import DashboardParentView
from dashboard.models import Course, ModuleItem
from common.util.get_modules import get_modules


class Module(DashboardParentView):
    template_name = "dashboard/module/list.html"

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)

        course: Course = context["course"]

        modules = get_modules(course.modules.all())

        context["title"] = f"{context['title']} Modules"
        context["sub_link"] = "module"
        context["modules"] = modules

        return context

    def get(self, request, *args, **kwargs):

        context = self.get_context_data(*args, **kwargs)

        return render(request, self.template_name, context)


class ModuleDetail(DashboardParentView):
    template_name = "dashboard/module/detail.html"

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)

        module_id = kwargs.pop("module_id", None)

        module = get_object_or_404(ModuleItem, pk=module_id)

        context["title"] = f"{module.title}"
        context["link"] = "course"
        context["sub_link"] = "module"

        context["module"] = module

        return context

    def get(self, request, *args, **kwargs):

        context = self.get_context_data(*args, **kwargs)

        return render(request, self.template_name, context)

dashboard/views/people.py
from django.shortcuts import render

from dashboard.models import Course

from dashboard.util.view import DashboardParentView


class PeopleList(DashboardParentView):
    template_name = "dashboard/people/list.html"

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)

        context["title"] = f"{context['title']} People"
        context["sub_link"] = "people"

        return context

    def get(self, request, *args, **kwargs):

        context = self.get_context_data(*args, **kwargs)

        course: Course = context["course"]

        professor = course.professor.user
        students = []
        enrollments = course.enrollments.all()

        for enrollment in enrollments:
            students.append(enrollment.student.user)

        context["professor"] = professor
        context["students"] = students

        return render(request, self.template_name, context)

dashboard/templates/dashboard/module/create.html
{% extends "base/base.html" %} 

{% load static %} 

{% block title %} {{ title }} {% endblock %} 

{% block extra_css %}

{% endblock extra_css %}

{% block content %}
{% endblock content %}

{% block extra_js %}{% endblock extra_js %}

dashboard/templates/dashboard/module/detail.html
{% extends "base/base.html" %} 

{% load static %} 

{% block title %} {{ title }} {% endblock %} 

{% block extra_css %}

{% endblock extra_css %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-2">
            <div class="d-block d-lg-none">
                <div class="position-relative w-100">
                    <button class="position-relative end-0 btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#sub-menu-collapse" aria-expanded="false" aria-controls="sub-menu-collapse">
                        Open Navigation
                    </button>
                </div>
                <div class="collapse" id="sub-menu-collapse">
                    <div class="list-group list-group-flush">
                        {% component "professor_sub_list" %}{% endcomponent %}
                    </div>
                </div>
            </div>
            <div class="list-group list-group-flush d-none d-lg-block">
                {% component "professor_sub_list" %}{% endcomponent %}
            </div>
        </div>
        <div class="col-lg-10">
        {% comment %} Content Here {% endcomment %}
            <div class="row">
                <div class="col-xs-1-12">
                    <div class="card">
                        <div class="card-body">
                            <h3 class="card-title">
                                <div class="hstack gap-3 d-flex justify-content-between">
                                    {{ module.title }}
                                    
                                    {% if user.profile.is_professor %}
                                    
                                        {% if module.is_published %}
                                            (Published)
                                        {% else %}
                                            (Unpublished)
                                        {% endif %}
                                    
                                    {% endif %}

                                    {% if user.profile.is_professor %}
                                        <div>
                                            {% if module.is_published %}
                                                <a href="#" class="btn btn-primary">
                                                    <i class="fa fa-eye-slash"></i>
                                                </a>
                                            {% else %}
                                                <a href="#" class="btn btn-primary">
                                                    <i class="fa fa-eye"></i>
                                                </a>
                                            {% endif %}
                                            <a href="#" class="btn btn-primary">
                                                <i class="fa fa-edit"></i> Edit
                                            </a>
                                        </div>
                                    {% endif %}
                                </div>
                            </h3>
                            <p class="card-text">{{ module.short_description }}</p>

                            <br />

                            {{ module.description }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block extra_js %}{% endblock extra_js %}

dashboard/templates/dashboard/module/list.html
{% extends "base/base.html" %} 

{% load static %} 

{% block title %} {{ title }} {% endblock %} 

{% block extra_css %}

{% endblock extra_css %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-2">
            <div class="d-block d-lg-none">
                <div class="position-relative w-100">
                    <button class="position-relative end-0 btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#sub-menu-collapse" aria-expanded="false" aria-controls="sub-menu-collapse">
                        Open Navigation
                    </button>
                </div>
                <div class="collapse" id="sub-menu-collapse">
                    <div class="list-group list-group-flush">
                        {% component "professor_sub_list" %}{% endcomponent %}
                    </div>
                </div>
            </div>
            <div class="list-group list-group-flush d-none d-lg-block">
                {% component "professor_sub_list" %}{% endcomponent %}
            </div>
        </div>
        <div class="col-lg-10">
        {% comment %} Content Here {% endcomment %}
            <div class="row">
                <div class="col-xs-1-12">
                    <div class="card">
                        <div class="card-body">
                            <h3 class="card-title">
                                <div class="hstack gap-3 d-flex justify-content-between">
                                    {{ course.title }}  Modules
                                    {% if perms.dashboard.add_moduleitem %}
                                        <a href="#" class="btn btn-success">
                                            <i class="fa fa-plus"></i> Add new module/s
                                        </a>
                                    {% endif %}
                                </div>
                            </h3>

                            <br />

                            <div class="d-flex flex-column gap-3">
                                {% component "module_list" %}{% endcomponent %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block extra_js %}{% endblock extra_js %}

dashboard/templates/dashboard/module/update.html
{% extends "base/base.html" %} 

{% load static %} 

{% block title %} {{ title }} {% endblock %} 

{% block extra_css %}

{% endblock extra_css %}

{% block content %}
{% endblock content %}

{% block extra_js %}{% endblock extra_js %}